### ISSUE TITLE
Writing a new SBtabDocument

### ISSUE THREAD

**Issue by eladnoor** [tlubitz/SBtab#56]
The option of creating an SBtabDocument from individual existing SBtabTables requires giving them unique filenames (even though these names are not used anywhere). Also, the function SBtabDocument.write() doesn't work unless one defines the SBtabDocument.delimiter attribute manually - which is probably a bug.

**Comment by tlubitz** [comment]
Fixed

**Comment by eladnoor** [comment]
I think the first issue is still not solved. In line 764 in SBtab.py, this check is performed:
`if sbtab.filename in self.sbtab_filenames:
            raise SBtabError('The SBtab could not be added it has the '
                            'same table name as an existing SBtab:'
                            ' %s.' % (sbtab.filename))
return`

Perhaps the intention was to check for duplicates in the table_name rather of the filename?

**Comment by tlubitz** [comment]
I am really not entirely sure why this check existed; I assume it belonged to the integrity of the web interface, but is not required anymore. I removed the check.

**Comment by tlubitz** [comment]
To be honest I do not recall why this check was necessary at some point. I think it was something about the integrity in the web interface. But I do not think that is required anymore, so I removed it completely.
